### ISSUE TITLE
Save Project profile

### ISSUE THREAD

**Issue by jlwt90** [jlwt90/jira-progress-report#2]
## Config File
It should allow users to have multiple project profiles.
We may use file name to distinguish the profile.

## YAML file format
```
metadata:
  created: xxxx (in ISO-8601 UTC)
  name: xxxx
spec:
  description: xxxx
  epics:
    - ticket: ABC-1
      mode: default
    - ticket: ABC-2
      mode: default
  template: xxx (refers to the template in `tpl` directory.
```
